coffee_shop_oriana:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: aec-students
      dataset: dbt_oriana
      threads: 8
      keyfile: ./coffee_shop_oriana/gcp-credentials.json