name: Run dbt test suite on PRs

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  push:
    branches:
      - '!main'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DBT_PROFILES_DIR: ./coffee_shop_oriana  # Specify the location of the profiles.yml file
      DBT_PROJECT_DIR: ./coffee_shop_oriana
      BIGQUERY_PROJECT_ID: aec-students  # Replace with your Google Cloud Project ID
      BIGQUERY_SERVICE_ACCOUNT_KEY: ${{ secrets.BIGQUERY_SERVICE_ACCOUNT_KEY }}

    steps:
      - name: Checkout PR code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # Checkout the specific commit of the pull request

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # Choose the Python version you need

      - name: Create GCP keyfile JSON
        run: |
          echo "${{ secrets.BIGQUERY_SERVICE_ACCOUNT_KEY }}" > gcp-credentials.json
          echo "$DBT_PROFILES_DIR"
          echo "$PWD"
          mv gcp-credentials.json "$DBT_PROFILES_DIR"  # Move the keyfile to the profiles directory

      - name: Install dbt-bigquery
        run: |
          pip install dbt-bigquery
          dbt --version

      - name: Run dbt
        run: |
          dbt run --profiles-dir "$DBT_PROFILES_DIR" --target dev --project-dir "$DBT_PROJECT_DIR"