name: Run dbt on BigQuery

on:
  push:
    branches:
      - main  # Replace with your branch name

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GCP_PROJECT_ID: your-project-id  # Replace with your Google Cloud Project ID
      BIGQUERY_SERVICE_ACCOUNT_KEY: ${{ secrets.BIGQUERY_SERVICE_ACCOUNT_KEY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  # Choose the Python version you need

    - name: Install dbt
      run: |
        pip install dbt-bigquery
        dbt --version

    - name: Set up GCP credentials and run dbt
      run: |
        echo "$BIGQUERY_SERVICE_ACCOUNT_KEY" > gcp-credentials.json
        gcloud auth activate-service-account --key-file=gcp-credentials.json --project="$GCP_PROJECT_ID"
        dbt run --profiles-dir .dbt --target dev