name: Run dbt test suite on PRs

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  push:
    branches:
      - '!main'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GCP_PROJECT_ID: aec-students  # Replace with your Google Cloud Project ID
      BIGQUERY_SERVICE_ACCOUNT_KEY: ${{ secrets.BIGQUERY_SERVICE_ACCOUNT_KEY }}

    steps:
      - name: Checkout PR code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # Checkout the specific commit of the pull request

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # Choose the Python version you need

      - name: Install dbt
        run: |
          pip install dbt-bigquery
          dbt --version

      - name: dbt debug
        run: dbt debug --profiles-dir $PWD

      - name: Set up GCP credentials and run dbt
        run: |
          echo "$BIGQUERY_SERVICE_ACCOUNT_KEY" > gcp-credentials.json
          gcloud auth activate-service-account --key-file=gcp-credentials.json --project="$GCP_PROJECT_ID"
      
      - name: Run dbt packages
        run: dbt deps

      - name: Run dbt
        run: dbt run
      
      - name: Run dbt test suite
        run: dbt test